### ISSUE TITLE
out of memory when training a BBPE tokenizer on a large corpus 

### ISSUE THREAD

**Issue by yucc-leon** [huggingface/tokenizers#1681]
Hi there, this may be stupid but I felt confused...
I compiled a corpus containing 20GB of pure raw text and wanted to train my **customized BBPE tokenizer**. 

With the guidance of your NLP course (https://huggingface.co/learn/nlp-course/chapter2/4. It's friendly and easy to understand BTW!) I used the same code, and it seemed good at first. But it **turned slow and ran out of memory soon** when merging. 

The program failed on servers with 1.5TB or 2TB memory. 
From some tutorials, the BPE tokenizer may need to do heavy statistics in memory. But I guess there should be better solutions like **multi-node training** for top players like OAI (with closed models) or huggingface (with OS models) to train their own tokenizers on very large corpus (**say 500GB texts or much more**). 

Anyone would kindly show me the way to do this in an industrialized style?

**Comment by ArthurZucker** [comment]
Hey! I think this is related to #1539 and we are fixing it! 🤗

**Comment by ArthurZucker** [comment]
We are doing a release to include this in a few days!

**Comment by sftse** [comment]
@yucc-leon 
Can you confirm the issue was solved?

**Comment by yucc-leon** [comment]
> @yucc-leon Can you confirm the issue was solved?

I'll test it in a few days and report the result here!

**Comment by frankang** [comment]
@sftse 
Hi, I still get the same OOM issue on the latest tokenizer version (Version: 0.21.1). When training on a ~20GB corpus, the program consumes over 1TB memory at the `Count pairs` step and got killed by the system.
Here is my training code:
```
tokenizer = AutoTokenizer.from_pretrained(base_tokenizer_name, token=args.token, trust_remote_code=True)
new_tokenizer = tokenizer.train_new_from_iterator(
    final_text_iterator,
    vocab_size=args.vocab_size,
    new_special_tokens=ADDITIONAL_SPECIAL_TOKENS
    )
```

**Comment by sftse** [comment]
@frankang 
Try to reduce the corpus, is there any amount of data on which the tokenizer successfully trains?

Provide minimal complete code that reproduces the problem, otherwise it is impossible to help.

**Comment by wchen99998** [comment]
I have been seeing this clear cache approach being mentioned in several issues that clearly it doesn't apply to, i.e. the training phase of BPE and iirc does not use the cache?

**Comment by sftse** [comment]
That is correct, see my [comment above](https://github.com/huggingface/tokenizers/issues/1681#issuecomment-2912539050).

@ArthurZucker Can this issue be reopened? #1795 seems to provide some hints to investigate this further.
